
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jarmi
 */
public class SlovnikFrame extends javax.swing.JFrame {

    
  // 0 == typeSk, 1 == typeEn
  int vyber;
  int vyberH;
  
  static Pair p;      
  private static  List<Pair> ps = new ArrayList<>();

  boolean testBezi = false;
  double body = 0.0;
  int nesprav = 0;
  int max = 0;
  int pocet = 0;
  int uspesnostc = 0;
  public static int pocetDvojic = 0;
   int last = 0;
    
  public SlovnikFrame() 
  {
      initComponents();
      readFile();
      dvojicePocet.setText(""+pocetDvojic);
      hratext.addFocusListener(new java.awt.event.FocusAdapter() {
       @Override
       public void focusGained(java.awt.event.FocusEvent evt) {
       hratext.setText("");
       nespravnetxt.setText("");
       }
        });
       hratext.addActionListener(new java.awt.event.ActionListener() {
       @Override
       public void actionPerformed(java.awt.event.ActionEvent evt) {
       potvrdithra.doClick();
       hratext.setText("");
       }
        });
       textnaSlovicko.addFocusListener(new java.awt.event.FocusAdapter() {
       @Override
       public void focusGained(java.awt.event.FocusEvent evt) {
       textnaSlovicko.setText("");
       }
        });
       textnaSlovicko.addActionListener(new java.awt.event.ActionListener() {
       @Override
       public void actionPerformed(java.awt.event.ActionEvent evt) {
       hladatb.doClick();
       }
        });
       
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hladanieGrup = new javax.swing.ButtonGroup();
        hraGrup = new javax.swing.ButtonGroup();
        upravaSlov = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hrastart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        skoremax = new javax.swing.JLabel();
        hladatb = new javax.swing.JButton();
        sktoEn1 = new javax.swing.JRadioButton();
        sktoEn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        entoSk = new javax.swing.JRadioButton();
        entoSk1 = new javax.swing.JRadioButton();
        textnaSlovicko = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hratext = new javax.swing.JTextField();
        spravneodpovedi = new javax.swing.JLabel();
        pocetnespravnych = new javax.swing.JLabel();
        stopt = new javax.swing.JButton();
        potvrdithra = new javax.swing.JButton();
        zadanie = new javax.swing.JLabel();
        nespravnetxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uspesnost = new javax.swing.JLabel();
        prekladSlova = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dvojicePocet = new javax.swing.JLabel();
        aktualizacia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 300));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(680, 660));
        setName("slovnik"); // NOI18N
        setPreferredSize(new java.awt.Dimension(780, 700));
        setSize(new java.awt.Dimension(714, 665));

        upravaSlov.setText("Úprava slov v slovníku");
        upravaSlov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDocu(evt);
            }
        });

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        hrastart.setText("Štart");
        hrastart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrastartActionPerformed(evt);
            }
        });

        jLabel2.setText("Nastavenie testu");

        jLabel3.setText("najvyššie skóre:");

        skoremax.setText("0");

        hladatb.setText("Hladať");
        hladatb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladatbActionPerformed(evt);
            }
        });

        hladanieGrup.add(sktoEn1);
        sktoEn1.setSelected(true);
        sktoEn1.setText("sk --> en");

        hraGrup.add(sktoEn);
        sktoEn.setText("sk --> en");

        jLabel5.setText("Preklad z :");

        jLabel6.setText("Preklad slova:");

        hraGrup.add(entoSk);
        entoSk.setSelected(true);
        entoSk.setText("en --> sk");

        hladanieGrup.add(entoSk1);
        entoSk1.setText("en --> sk");

        textnaSlovicko.setText("Zadaj slovo");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Počet nesprávne zodpovedaných slov");

        jLabel4.setText("Počet správne zodpovedaných slov");

        hratext.setText("Zadaj slovo");

        spravneodpovedi.setText("0");

        pocetnespravnych.setText("0");

        stopt.setText("Stop");
        stopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoptActionPerformed(evt);
            }
        });

        potvrdithra.setText("potvrdit");
        potvrdithra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdithraActionPerformed(evt);
            }
        });

        jLabel8.setText("Úspešnosť");

        uspesnost.setText("0 %");

        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hratext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(spravneodpovedi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pocetnespravnych, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stopt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(potvrdithra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(zadanie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nespravnetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(uspesnost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(zadanie, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hratext, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(potvrdithra)
                            .addComponent(nespravnetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stopt)
                                .addGap(23, 23, 23))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pocetnespravnych, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uspesnost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(30, Short.MAX_VALUE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(spravneodpovedi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spravneodpovedi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pocetnespravnych)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(zadanie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hratext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nespravnetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uspesnost)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potvrdithra))
                .addGap(14, 14, 14))
        );

        jLabel9.setText("Počet dvojic v slovníku");

        aktualizacia.setText("Aktualizovať");
        aktualizacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktualizaciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sktoEn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entoSk1))
                    .addComponent(upravaSlov)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dvojicePocet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hladatb)
                    .addComponent(hrastart)
                    .addComponent(jLabel2)
                    .addComponent(textnaSlovicko, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prekladSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(entoSk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sktoEn)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skoremax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aktualizacia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upravaSlov)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(dvojicePocet, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aktualizacia)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sktoEn1)
                    .addComponent(entoSk1))
                .addGap(8, 8, 8)
                .addComponent(textnaSlovicko, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prekladSlova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hladatb)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entoSk)
                    .addComponent(sktoEn)
                    .addComponent(jLabel3)
                    .addComponent(skoremax))
                .addGap(24, 24, 24)
                .addComponent(hrastart)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(714, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void guess()
	{
        Random r = new Random();
		
        if (ps.isEmpty()) {
        zadanie.setText("Slovník je prázdny.");
        return;
            }
       
         int i = r.nextInt(ps.size());
         result:
         if(i==last){
             i = r.nextInt(ps.size());
             break result;
         }
         last = i;
         p = ps.get(i);
         String f = (vyber == 0) ? p.en : p.sk;
         zadanie.setText(f);
	}
	
    
    public  void readFile()
    {
     String[] ls = ReadWriter.readLines(ReadWriter.getFile("slovnik"));	
     int count = 0;
     pocetDvojic = ls.length;
     for (int i = 0; i < ls.length; i++)
     {
      String[] sp = ls[i].split(" ");
      if(sp.length == 2)
      {
       ps.add(new Pair(sp[0], sp[1]));
       count = i+1;
      }
      
     }
      dvojicePocet.setText(""+count);
    }
    
   private static void pripravSubor() {
    try {
        
        String cestaPlocha = System.getProperty("user.home") + File.separator + "Desktop";
       File slovnikSubor  = new File(cestaPlocha + File.separator + "slovnik.txt");
        if (!slovnikSubor.exists()) {
            if (slovnikSubor.createNewFile()) {
                System.out.println("Súbor bol vytvorený.");
            } else {
                System.out.println("Nepodarilo sa vytvoriť súbor.");
            }
        } else {
            System.out.println("Subor uz existuje.");
        }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
        
    private void potvrdithraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdithraActionPerformed
     if (!testBezi) return;
     pocet++;
     String odpoved = hratext.getText().trim();
     boolean spravne = false;
     
     if (vyber == 0 && odpoved.equalsIgnoreCase(p.sk)) {
         spravne = true;
     } else if (vyber == 1 && odpoved.equalsIgnoreCase(p.en)) {
         spravne = true;
    }

    if (spravne) {
        body++;
        if(max <= body) max =  (int)body;
        spravneodpovedi.setText(""+(int) body);
        nespravnetxt.setText("Správne!");
        skoremax.setText(""+max);
    } else {
        nesprav++;
        pocetnespravnych.setText(""+nesprav);
        nespravnetxt.setText("Zle! Správne bolo: " + (vyber == 0 ? p.sk : p.en));
    }
    
     uspesnostc = (int) ((body/ pocet)*100);
     uspesnost.setText(uspesnostc + " %");

    guess();
    }//GEN-LAST:event_potvrdithraActionPerformed
    
    private void editDocu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDocu
    try {
        // Získaj cestu k súboru slovnik.txt na ploche
        String cestaPlocha = System.getProperty("user.home") + File.separator + "Desktop";
        File subor = new File(cestaPlocha + File.separator + "slovnik.txt");
        // Ak súbor ešte neexistuje, vytvor ho (ale neprepisuj)
        if (!subor.exists()) {
            subor.createNewFile();
        }
        
        // Otvor súbor v predvolenom textovom editore
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            desktop.open(subor);
            readFile();
        } else {
            System.out.println("Desktop nie je podporovaný na tomto systéme.");
        }

    } catch (IOException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_editDocu

    private void hrastartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrastartActionPerformed
    testBezi = true;
    pocet = 0;
    body = 0.0;
    nesprav = 0;
    spravneodpovedi.setText("0");
    pocetnespravnych.setText("0");
    uspesnost.setText("0 %");
    if (sktoEn.isSelected()) vyber = 1;
    else vyber = 0;
    readFile();
    guess();
    }//GEN-LAST:event_hrastartActionPerformed

    private void stoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoptActionPerformed
     if(testBezi)
     {
      testBezi = false;
      zadanie.setText("Test ukončený.");
      hratext.setText("Zadaj slovo");
      nespravnetxt.setText("");
     }
    }//GEN-LAST:event_stoptActionPerformed

    private void hladatbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladatbActionPerformed
        readFile();
        String hladane = textnaSlovicko.getText().trim();
    boolean najdene = false;
    
     if (sktoEn1.isSelected()) vyberH = 1;
     else vyberH = 0;
    
   for (int i = 0; i < ps.size(); i++) {
     p = ps.get(i);  
    
    if (vyberH == 0 && hladane.equalsIgnoreCase(p.en)) {
        prekladSlova.setText(p.sk);
        najdene = true;
        break;
    } else if (vyberH == 1 && hladane.equalsIgnoreCase(p.sk)) {
        prekladSlova.setText(p.en);
        najdene = true;
        break;
        }
    }

    if (!najdene) {
        int volba = JOptionPane.showConfirmDialog(
            this,
            "Slovo nebolo nájdené. Chcete ho pridať?",
            "Slovo nenájdené",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (volba == JOptionPane.YES_OPTION) {
             editDocu(evt);
        }
    }
    }//GEN-LAST:event_hladatbActionPerformed

    private void aktualizaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktualizaciaActionPerformed
     readFile();
    }//GEN-LAST:event_aktualizaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlovnikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlovnikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlovnikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlovnikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        pripravSubor();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlovnikFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aktualizacia;
    private javax.swing.JLabel dvojicePocet;
    private javax.swing.JRadioButton entoSk;
    private javax.swing.JRadioButton entoSk1;
    private javax.swing.ButtonGroup hladanieGrup;
    private javax.swing.JButton hladatb;
    private javax.swing.ButtonGroup hraGrup;
    private javax.swing.JButton hrastart;
    private javax.swing.JTextField hratext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nespravnetxt;
    private javax.swing.JLabel pocetnespravnych;
    private javax.swing.JButton potvrdithra;
    private javax.swing.JLabel prekladSlova;
    private javax.swing.JLabel skoremax;
    private javax.swing.JRadioButton sktoEn;
    private javax.swing.JRadioButton sktoEn1;
    private javax.swing.JLabel spravneodpovedi;
    private javax.swing.JButton stopt;
    private javax.swing.JTextField textnaSlovicko;
    private javax.swing.JButton upravaSlov;
    private javax.swing.JLabel uspesnost;
    private javax.swing.JLabel zadanie;
    // End of variables declaration//GEN-END:variables
}
